### ISSUE TITLE
[Feature request] 출시 전 수정

### ISSUE THREAD

**Issue by feldblume5263** [hasen-sprung/iOS_Canvas#111]
### 최우선
- [x] core data 수정
- [x] 설정창 전체적인 에러 수정 -
- [x] canvas title 삭제 -
- [x] info view 도형 -> 최근 메모 (클릭시 도형 애니메이션) -
- [x] 홈버튼 있는 기종 status bar 삭제 +
- [x] create view auto layout +
- [x] listview navigationview 쪽 높이 맞추기
- [x] mainView 가이드도형 처음에만 나타나게 수정
- [x] 테스트용 시더 생성
- [x] 버튼 회색 비활성화 - 세팅 무명작가변경시, 처음이용시 이름입력시
- [x] info greeting 클릭시, 랜덤으로 보여지게끔

### 나중우선
- [x] 탭틱
- [x] text 입력 뉴라인 enter byte 인식
- [x] placeholer -> text
- [ ] setting 창 모드 설명
- [ ] firebase error 분석툴 설치

**Comment by ejei0g** [comment]
하단 두 개 새롭게 feature 등록
