### ISSUE TITLE
[Bug report] 뒤로가기 제스쳐

### ISSUE THREAD

**Issue by ejei0g** [hasen-sprung/iOS_Canvas#115]
## Description of the bug (required)
- [x] 뒤로가기 제스쳐가 왼쪽에서만 가능해야 함
- [x] 리스트창의 중간 지점, 오른쪽 지점에서 제스처를 실행해도 뒤로 가버림 (사파리 뒤로가기 제스쳐 참고할 것)

**Comment by feldblume5263** [comment]
반영완료하였습니다!!
