### ISSUE TITLE
[Feature request] 설정창에서 main진입점 변경할 수 있게 추가

### ISSUE THREAD

**Issue by ejei0g** [hasen-sprung/iOS_Canvas#121]
## New features needed
- 기존방식 : 메인뷰- +버튼클릭 - 게이지창
- 설정에서 옵션 변경 시: 게이지창이 바로 뜨게

**Comment by feldblume5263** [comment]
진입점 옵션 변경 완료

해당 구간
1. 처음에 앱을 켤 때
2. 백그라운드에서 포그라운드로 돌아올 떄

**Comment by feldblume5263** [comment]
리스트창과 세팅창에서 백그라운드에서 포그라운드로 돌아올 떄 적용할 것인지는 논의가 필요합니다.

**Comment by ejei0g** [comment]
Cancel Update
